### ISSUE TITLE
Adding description for the environment scripts& containers

### ISSUE THREAD

**Issue by IdanBanani** [one2blame/heaplab#3]
May you kindly add some explanation on the motivation/reasons for:
1.Adding a docker file for each challenge 
2.simulating a challenge server on local host
3.Using python2.7 instead of 3 (how did you even manage to add pwntools to it?)

**Comment by one2blame** [comment]
Hey @IdanBanani !

`Dockerfile`s for the `heaplab` challenges aren't completely necessary, especially since each program's `RPATH` is modified to point to the correct `glibc`. I've just added these `Dockerfile`s because this is how I usually setup my local testing environment for CTF challenges - to keep the environment and dependencies in a deterministic state and separate from my host's installed packages, etc.

I like to simulate the challenge on `localhost`because in a real-world scenario you're likely to be exploiting the target over the network.

As for **Python 2.7**, I was working on Ubuntu 18.04 at the time which still has `apt` support for Python 2. I believe `pwntools` still has stable releases for Python 2, but yes, everyone should use Python 3 whenever possible.

**Comment by IdanBanani** [comment]
Thanks. 
Do you run the .sh script on an Ubuntu 18.04 machine which has docker installed 
or it is suppose to work on any NIX os? (I don't really know how the magic behind docker works, I'll be surprised if your script pulls an Ubuntu docker image for each challenge (there's a docker file and .sh file for each challenge here). 
but it does seems like it creates some kind of an isolated container

**Comment by one2blame** [comment]
@IdanBanani Right, the containers create isolated environments for the target binaries in order to resolve all of their dependencies, making for consistent exploitation across any NIX operating system. So as long as you have the `docker` package installed on your operating system, the `solve.py` script will work against the target.

There's a different container for each challenge, but each one actually isn't that large. Once you pull the base container for Ubuntu into your Docker cache, that base container will be reused to create / start the other images. Docker works to save as much space on your operating system as possible.

Finally, Docker is awesome! Really good for creating CTFs and packaging final releases for exploit code, etc. There's not that much magic to it - Docker containers can be viewed as lightweight virtual machines. The biggest difference is that, unlike virtual machines, Docker containers aren't using virtual CPUs and a Hypervisor - they make system calls directly to your host machine's CPU.

**Comment by IdanBanani** [comment]
Thank you.
I should probably try it on an newer version of Ubuntu (like 20)

Because for some reason, it doesn't go smooth +
Still need to figure out the logic behind deploy.sh & dockerfile
![Error](https://user-images.githubusercontent.com/26879273/114565789-4d320900-9c7a-11eb-9dbe-9646a08c793d.png)

**Comment by one2blame** [comment]
Run `deploy.sh` as such:

```bash
sudo ./deploy.sh 4444
```

The default port the Docker container runs on is `4444`.
